# -*- coding: utf-8 -*-
"""Trabajo_grupo5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CjUicw1T4G5biKSSZPlEDdWXmhRb8Oof
"""

import pandas as pd
base_de_datos='/content/BASE DE DATOS.xlsx'
base_de_datos_df=pd.read_excel(base_de_datos)
base_de_datos_df.head()

import pandas as pd
def Columns(df):
  columnas = df.columns
  list_columns = list(columnas)
  return list_columns

df= base_de_datos_df
def añadir_fila():
  global df
  dicc_fila = {}
  columnas_df = Columns(df) 
  for columna in columnas_df:
    dicc_fila[columna] = input('Ingrese valor de la columna {} '.format(columna))
  df= df.append(dicc_fila, ignore_index = True)

Nombre=input('Escribe tu nombre: ')
print('Hola', Nombre, '¿Qué operación deseas realizar?')
print('1. Ingresar nuevos datos')
print('2. Filtrar datos')
print('3. Solicitar gráfico')
print('4. Generar nuevas características a los datos')
print('5. Datos estadísticos')
decisión=int(input("Ingrese su desición, elija un número: "))
print("Haz introducido el número {} ".format(decisión))

while decisión==1:
  añadir_fila()
  display(df.tail(10))    
  decisión=int(input("Ingrese su desición, elija un número: "))
  print("Haz introducido el número {} ".format(decisión))
while decisión==2:
  print('¿Qué deseas filtrar?, Elige entre éstas opciones: ')
  print('a. Fecha')
  print('b. Código')
  print('c. Artículo')
  print('d. Unidad')
  print('e. Precio Unitario')
  print('f. Cantidad')
  print('g. Ventas')
  print('h. Comisión')
  decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='a':
    base_de_datos_df.describe()
    fecha=input('Elija una fecha: ')
    respuestaa =base_de_datos_df.loc[base_de_datos_df['Fecha'] == fecha]
    print(respuestaa)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='b':
    base_de_datos_df.describe()
    código=input('Elija un código: ')
    respuestab =base_de_datos_df.loc[base_de_datos_df['Código'] == código]
    print(respuestab)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='c':
    base_de_datos_df.describe()
    artículo=input('Elija un artículo: ')
    respuestac =base_de_datos_df.loc[base_de_datos_df['Artículo'] == artículo]
    print(respuestac)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='d':
    base_de_datos_df.describe()
    unidad=input('Elija una unidad: ')
    respuestad =base_de_datos_df.loc[base_de_datos_df['Unidad'] == unidad]
    print(respuestad)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='e':
    base_de_datos_df.describe()
    precio_unitario=float(input('Elija un precio unitario: '))
    respuestae =base_de_datos_df.loc[base_de_datos_df['Precio Unitario'] == precio_unitario]
    print(respuestae)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='f':
    base_de_datos_df.describe()
    cantidad=float(input('Elija una canidad: '))
    respuestaf =base_de_datos_df.loc[base_de_datos_df['Cantidad'] == cantidad]
    print(respuestaf)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='g':
    base_de_datos_df.describe()
    venta=float(input('Elija una venta: '))
    respuestag =base_de_datos_df.loc[base_de_datos_df['Ventas'] == venta]
    print(respuestag)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  while decisión2=='h':
    base_de_datos_df.describe()
    comisión=float(input('Elija una comisión: '))
    respuestah =base_de_datos_df.loc[base_de_datos_df['Comisión'] == comisión]
    print(respuestah)
    decisión2=input("Ingrese su decisión, elija una letra: ")
  else:
    print('No se ingresó ninguna de las letras')
    print('cerrar')
  decisión=int(input("Ingrese su desición, elija un número: "))
  print("Haz introducido el número {} ".format(decisión))
while decisión==3:
  import numpy as np
  import matplotlib.pyplot as plt
  from matplotlib.pylab import subplots
  Artículo = list(base_de_datos_df["Artículo"])
  Precio_Unitario = list(base_de_datos_df['Precio Unitario'])
  Cantidad = list(base_de_datos_df['Cantidad'])
  Ventas = list(base_de_datos_df['Ventas'])
  plt.scatter(Precio_Unitario,Artículo,c = Cantidad,s = Ventas,alpha=0.5, cmap='viridis')
  plt.colorbar()
  decisión=int(input("Ingrese su desición, elija un número: "))
  print("Haz introducido el número {} ".format(decisión))
while decisión==4:
  print('¿Qué característica desea agregrar?:')
  print('I. Lugar de distribución')
  print('II. Nombre del distribuidor')
  decisión4=input('Ingrese su decisión, elija I o II: ')
  while decisión4=='I':
    base_de_datos_df['Lugar de distribución'] = ['lima','piura','chiclayo','tumbes','loreto','ucayali','cajamarca','tacna']
    display(base_de_datos_df)
    decisión4=input('Ingrese su decisión, elija I o II: ')
  while decisión4=='II':
    base_de_datos_df['Nombre del distribuidor'] = ['daniel','Josue','brenda','luz','eduardo','gustavo','willy','mateo']
    display(base_de_datos_df)
    decisión4=input('Ingrese su decisión, elija I o II: ')
  else:
    print('no se deseó agregar nada')
    print('cerrar')
  decisión=int(input("Ingrese su desición, elija un número: "))
  print("Haz introducido el número {} ".format(decisión))
while decisión==5:
  print('¿Qué gráfico estadistico deseas visualizar?:')
  print('A. Precio Unitario vs Ventas')
  print('B. Precio Unitario vs Cantidad')
  print('C. Ventas vs Comisión')
  decisión5=input('Elija una Opción: ')
  while decisión5=='A':
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.relplot(x = 'Precio Unitario', y = 'Ventas', data = base_de_datos_df)
    plt.show()
    break
    decisión5=input('Elija una Opción: ')
    print("Haz introducido el número {} ".format(decisión5))
  while decisión5=='B':
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.relplot(x = 'Precio Unitario', y = 'Cantidad', data = base_de_datos_df)
    plt.show()
    break
    decisión5=input('Elija una Opción: ')
    print("Haz introducido el número {} ".format(decisión5))
  while decisión5=='C':
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.relplot(x = 'Ventas', y = 'Comisión', data = base_de_datos_df)
    plt.show()
    break
    decisión5=input('Elija una Opción: ')
    print("Haz introducido el número {} ".format(decisión5))
  else:
    print('No desea visualizar nada')
    break
else:
  print('Error')
  print('No Ingresó ninguna de las opciones')
  print('Adiós {}'.format(Nombre))